
export interface DoctorDetails {
    yearInfo: number;
    regDate: string;
    doctorId: number;
    salutation?: string | null;
    firstName: string;
    middleName?: string | null;
    lastName?: string | null;
    phoneNo?: string | null;
    emailId?: string | null;
    gender?: string | null;
    bloodGroup?: string | null;
    parentName: string;
    birthDate?: string | null;
    isNewDoctor: boolean;
    checkExistingUser: boolean;
    birthDateStr?: string | null;
    birthPlace?: string | null;
    nationality?: string | null;
    eligbleToVote?: boolean | null;
    adharNo?: string | null;
    uprnNo?: string | null;
    doctorEducationId?: number | null;
    college?: string | null;
    doctorDegree: string;
    university: string;
    otherSubject?: string | null;
    monthOfPass?: string | null;
    yearOfPassing: string;
    smcId: number;
    registrationDate?: string | null;
    registrationNo: string;
    smcName: string;
    homeAddress?: string | null;
    officeAddress?: string | null;
    address: string;
    addressLine1: string;
    addressLine2?: string | null;
    economicStatus?: string | null;
    city?: string | null;
    state?: string | null;
    country?: string | null;
    pincode?: string | null;
    photos?: string | null;
    doctRegistrationNo?: string | null;
    universityId_view?: number | null;
    universityId?: number | null;
    monthandyearOfPass: string;
    passoutCollege?: string | null;
    collegeId?: number | null;
    stateId?: number | null;
    catagory?: string | null;
    catagory_view: string;
    role?: string | null;
    registrationDatePrevious?: string | null;
    registrationNoPrevious?: string | null;
    smcNamePrevious?: string | null;
    uprnNoPrevious?: string | null;
    removedStatus: boolean;
    removedOn?: string | null;
    restoredStatus?: boolean | null;
    restoredOn?: string | null;
    remarks?: string | null;
    regnNo?: string | null;
    smcIds?: number[] | null;
    trasanctionStatus?: string | null;
    addlqual1?: string | null;
    addlqualyear1?: string | null;
    addlqualuniv1?: string | null;
    addlqual2?: string | null;
    addlqualyear2?: string | null;
    addlqualuniv2?: string | null;
    addlqual3?: string | null;
    addlqualyear3?: string | null;
    addlqualuniv3?: string | null;
    patientfirstName?: string | null;
    patientmiddleName?: string | null;
    patientlastName?: string | null;
    patientphoneNo?: string | null;
    patientemailId?: string | null;
    appealBy?: string | null;
    altphone?: string | null;
    landLineNo?: string | null;
    patientlandLineNo?: string | null;
    patientaltphone?: string | null;
    picName?: string | null;
    signatureName?: string | null;
    stateMedicalCouncil?: string | null;
    countryType?: string | null;
    dateOfBirth?: string | null;
    universityName?: string | null;
    qualification?: string | null;
    imrNumber?: string | null;
    smcCode?: string | null;
}


[
    {
        yearInfo: 2012,
        regDate: '13/04/2012',
        doctorId: 1067608,
        salutation: null,
        firstName: 'ANITHA. C',
        middleName: null,
        lastName: null,
        phoneNo: null,
        emailId: null,
        gender: null,
        bloodGroup: null,
        parentName: 'LATE C. RAMAIAH',
        birthDate: null,
        isNewDoctor: false,
        checkExistingUser: false,
        birthDateStr: '02/10/1988',
        birthPlace: null,
        nationality: null,
        eligbleToVote: null,
        adharNo: null,
        uprnNo: null,
        doctorEducationId: null,
        college: null,
        doctorDegree: 'MBBS',
        university: 'U.R.G.H.S',
        otherSubject: null,
        monthOfPass: null,
        yearOfPassing: '2012',
        smcId: 13,
        registrationDate: null,
        registrationNo: '96060',
        smcName: 'Karnataka Medical Council',
        homeAddress: null,
        officeAddress: null,
        address: '# 758, MES ROAD, MUTHYALAMMA NAGAR, GOKULA (POST) BANGALORE- 560 054. MOBILE: 8861426927.',
        officeaddress: null,
        addressLine1: '# 758, MES ROAD, MUTHYALAMMA NAGAR, GOKULA (POST) BANGALORE- 560 054. MOBILE: 8861426927.',
        addressLine2: null,
        economicStatus: null,
        city: null,
        state: null,
        country: null,
        pincode: null,
        photos: null,
        doctRegistrationNo: null,
        universityId_view: null,
        universityId: null,
        monthandyearOfPass: '2012',
        passoutCollege: null,
        collegeId: null,
        stateId: null,
        catagory: null,
        catagory_view: 'N/A',
        role: null,
        registrationDatePrevious: null,
        registrationNoPrevious: null,
        smcNamePrevious: null,
        uprnNoPrevious: null,
        removedStatus: false,
        removedOn: null,
        restoredStatus: null,
        restoredOn: null,
        remarks: null,
        regnNo: null,
        smcIds: null,
        trasanctionStatus: null,
        addlqual1: null,
        addlqualyear1: null,
        addlqualuniv1: null,
        addlqual2: null,
        addlqualyear2: null,
        addlqualuniv2: null,
        addlqual3: null,
        addlqualyear3: null,
        addlqualuniv3: null,
        patientfirstName: null,
        patientmiddleName: null,
        patientlastName: null,
        patientphoneNo: null,
        patientemailId: null,
        appealBy: null,
        altphone: null,
        landLineNo: null,
        patientlandLineNo: null,
        patientaltphone: null,
        picName: null,
        signatureName: null,
        stateMedicalCouncil: null,
        countryType: null,
        dateOfBirth: null,
        universityName: null,
        qualification: null,
        imrNumber: null,
        smcCode: null
    },
    {
        yearInfo: 2012,
        regDate: '22/03/2012',
        doctorId: 1078222,
        salutation: null,
        firstName: 'MRUDUL SHASHIKANT SHINGE',
        middleName: null,
        lastName: null,
        phoneNo: null,
        emailId: null,
        gender: null,
        bloodGroup: null,
        parentName: 'SHASHIKANT SHINGE',
        birthDate: null,
        isNewDoctor: false,
        checkExistingUser: false,
        birthDateStr: '02/06/1983',
        birthPlace: null,
        nationality: null,
        eligbleToVote: null,
        adharNo: null,
        uprnNo: null,
        doctorEducationId: null,
        college: null,
        doctorDegree: 'MBBS',
        university: 'U.Baba Farid',
        otherSubject: null,
        monthOfPass: null,
        yearOfPassing: '2008',
        smcId: 21,
        registrationDate: null,
        registrationNo: '96060',
        smcName: 'Tamil Nadu Medical Council',
        homeAddress: null,
        officeAddress: null,
        address: 'S.D.A.MISSION COMPOUND,MARKET YARD POST,SALISBURY PARK,PUNE,MAHARASHTRA.411037',
        officeaddress: null,
        addressLine1: 'S.D.A.MISSION COMPOUND,MARKET YARD POST,SALISBURY PARK,PUNE,MAHARASHTRA.411037',
        addressLine2: null,
        economicStatus: null,
        city: null,
        state: null,
        country: null,
        pincode: null,
        photos: null,
        doctRegistrationNo: null,
        universityId_view: null,
        universityId: null,
        monthandyearOfPass: '2008',
        passoutCollege: null,
        collegeId: null,
        stateId: null,
        catagory: null,
        catagory_view: 'N/A',
        role: null,
        registrationDatePrevious: null,
        registrationNoPrevious: null,
        smcNamePrevious: null,
        uprnNoPrevious: null,
        removedStatus: false,
        removedOn: null,
        restoredStatus: null,
        restoredOn: null,
        remarks: null,
        regnNo: null,
        smcIds: null,
        trasanctionStatus: null,
        addlqual1: null,
        addlqualyear1: null,
        addlqualuniv1: null,
        addlqual2: null,
        addlqualyear2: null,
        addlqualuniv2: null,
        addlqual3: null,
        addlqualyear3: null,
        addlqualuniv3: null,
        patientfirstName: null,
        patientmiddleName: null,
        patientlastName: null,
        patientphoneNo: null,
        patientemailId: null,
        appealBy: null,
        altphone: null,
        landLineNo: null,
        patientlandLineNo: null,
        patientaltphone: null,
        picName: null,
        signatureName: null,
        stateMedicalCouncil: null,
        countryType: null,
        dateOfBirth: null,
        universityName: null,
        qualification: null,
        imrNumber: null,
        smcCode: null
    },
    {
        yearInfo: 2016,
        regDate: '20/09/2016',
        doctorId: 1312883,
        salutation: null,
        firstName: 'BANDAM SRINIVAS',
        middleName: null,
        lastName: null,
        phoneNo: null,
        emailId: null,
        gender: null,
        bloodGroup: null,
        parentName: 'BANDAM RADHAKRISHNAIAH',
        birthDate: null,
        isNewDoctor: false,
        checkExistingUser: false,
        birthDateStr: '05/06/1992',
        birthPlace: null,
        nationality: null,
        eligbleToVote: null,
        adharNo: null,
        uprnNo: null,
        doctorEducationId: null,
        college: null,
        doctorDegree: 'MBBS',
        university: 'Dr. NTR University of Health Sciences; Vijayawada',
        otherSubject: null,
        monthOfPass: null,
        yearOfPassing: '2016',
        smcId: 1,
        registrationDate: null,
        registrationNo: '96060',
        smcName: 'Andhra Pradesh Medical Council',
        homeAddress: null,
        officeAddress: null,
        address: '3-47,KURAKULAPALLE,,MAHAL(PO),KALIKIRI(M),CHITTOOR DT,Andhra Pradesh,517235',
        officeaddress: null,
        addressLine1: '3-47,KURAKULAPALLE,,MAHAL(PO),KALIKIRI(M),CHITTOOR DT,Andhra Pradesh,517235',
        addressLine2: null,
        economicStatus: null,
        city: null,
        state: null,
        country: null,
        pincode: null,
        photos: null,
        doctRegistrationNo: null,
        universityId_view: null,
        universityId: null,
        monthandyearOfPass: '2016',
        passoutCollege: null,
        collegeId: null,
        stateId: null,
        catagory: null,
        catagory_view: 'N/A',
        role: null,
        registrationDatePrevious: null,
        registrationNoPrevious: null,
        smcNamePrevious: null,
        uprnNoPrevious: null,
        removedStatus: false,
        removedOn: null,
        restoredStatus: null,
        restoredOn: null,
        remarks: null,
        regnNo: null,
        smcIds: null,
        trasanctionStatus: null,
        addlqual1: ' ',
        addlqualyear1: ' ',
        addlqualuniv1: ' ',
        addlqual2: ' ',
        addlqualyear2: ' ',
        addlqualuniv2: ' ',
        addlqual3: ' ',
        addlqualyear3: ' ',
        addlqualuniv3: ' ',
        patientfirstName: null,
        patientmiddleName: null,
        patientlastName: null,
        patientphoneNo: null,
        patientemailId: null,
        appealBy: null,
        altphone: null,
        landLineNo: null,
        patientlandLineNo: null,
        patientaltphone: null,
        picName: null,
        signatureName: null,
        stateMedicalCouncil: null,
        countryType: null,
        dateOfBirth: null,
        universityName: null,
        qualification: null,
        imrNumber: null,
        smcCode: null
    },
    {
        yearInfo: 2019,
        regDate: '05/09/2019',
        doctorId: 1206482,
        salutation: null,
        firstName: 'MOHITE TEJAS SAMPATRAO',
        middleName: null,
        lastName: null,
        phoneNo: null,
        emailId: null,
        gender: null,
        bloodGroup: null,
        parentName: 'MOHITE SAMPATRAO GANPATRAO',
        birthDate: null,
        isNewDoctor: false,
        checkExistingUser: false,
        birthDateStr: '02/03/1996',
        birthPlace: null,
        nationality: null,
        eligbleToVote: null,
        adharNo: null,
        uprnNo: null,
        doctorEducationId: null,
        college: '',
        doctorDegree: 'M.B.B.S.',
        university: 'KIMS KARAD',
        otherSubject: null,
        monthOfPass: null,
        yearOfPassing: '2019',
        smcId: 16,
        registrationDate: null,
        registrationNo: '2019096060',
        smcName: 'Maharashtra Medical Council',
        homeAddress: null,
        officeAddress: null,
        address: 'AT POST BELAWADE BK. TAL-KARAD, \r\nDIST-SATARA, MAHARASHTRA-',
        officeaddress: null,
        addressLine1: 'AT POST BELAWADE BK. TAL-KARAD, \r\nDIST-SATARA, MAHARASHTRA-',
        addressLine2: null,
        economicStatus: null,
        city: null,
        state: null,
        country: null,
        pincode: null,
        photos: null,
        doctRegistrationNo: null,
        universityId_view: null,
        universityId: null,
        monthandyearOfPass: '2019',
        passoutCollege: null,
        collegeId: null,
        stateId: null,
        catagory: null,
        catagory_view: 'N/A',
        role: null,
        registrationDatePrevious: null,
        registrationNoPrevious: null,
        smcNamePrevious: null,
        uprnNoPrevious: null,
        removedStatus: null,
        removedOn: null,
        restoredStatus: null,
        restoredOn: null,
        remarks: null,
        regnNo: null,
        smcIds: null,
        trasanctionStatus: null,
        addlqual1: '',
        addlqualyear1: '',
        addlqualuniv1: '',
        addlqual2: '',
        addlqualyear2: '',
        addlqualuniv2: '',
        addlqual3: '',
        addlqualyear3: '',
        addlqualuniv3: '',
        patientfirstName: null,
        patientmiddleName: null,
        patientlastName: null,
        patientphoneNo: null,
        patientemailId: null,
        appealBy: null,
        altphone: null,
        landLineNo: null,
        patientlandLineNo: null,
        patientaltphone: null,
        picName: null,
        signatureName: null,
        stateMedicalCouncil: null,
        countryType: null,
        dateOfBirth: null,
        universityName: null,
        qualification: null,
        imrNumber: null,
        smcCode: null
    },
    {
        yearInfo: 2021,
        regDate: '07/10/2021',
        doctorId: 12454772,
        salutation: null,
        firstName: 'YASHASWI  SINGH',
        middleName: null,
        lastName: null,
        phoneNo: null,
        emailId: null,
        gender: null,
        bloodGroup: null,
        parentName: 'UPENDRA KUMAR SINGH',
        birthDate: null,
        isNewDoctor: false,
        checkExistingUser: false,
        birthDateStr: '01/03/1985',
        birthPlace: null,
        nationality: null,
        eligbleToVote: null,
        adharNo: null,
        uprnNo: null,
        doctorEducationId: null,
        college: '',
        doctorDegree: '',
        university: '',
        otherSubject: null,
        monthOfPass: null,
        yearOfPassing: '',
        smcId: 23,
        registrationDate: null,
        registrationNo: '96060',
        smcName: 'Uttar Pradesh Medical Council',
        homeAddress: null,
        officeAddress: null,
        address: 'MAA CHARATABLE HOSPITAL RAMPURMAHABAL KHORIPAKAR, BALLIA-277001 UTTAR PRADESH',
        officeaddress: null,
        addressLine1: 'MAA CHARATABLE HOSPITAL RAMPURMAHABAL KHORIPAKAR, BALLIA-277001 UTTAR PRADESH',
        addressLine2: null,
        economicStatus: null,
        city: null,
        state: null,
        country: null,
        pincode: null,
        photos: null,
        doctRegistrationNo: null,
        universityId_view: null,
        universityId: null,
        monthandyearOfPass: '',
        passoutCollege: null,
        collegeId: null,
        stateId: null,
        catagory: null,
        catagory_view: 'N/A',
        role: null,
        registrationDatePrevious: null,
        registrationNoPrevious: null,
        smcNamePrevious: null,
        uprnNoPrevious: null,
        removedStatus: null,
        removedOn: null,
        restoredStatus: null,
        restoredOn: null,
        remarks: null,
        regnNo: null,
        smcIds: null,
        trasanctionStatus: null,
        addlqual1: '',
        addlqualyear1: '',
        addlqualuniv1: '',
        addlqual2: '',
        addlqualyear2: '',
        addlqualuniv2: '',
        addlqual3: '',
        addlqualyear3: '',
        addlqualuniv3: '',
        patientfirstName: null,
        patientmiddleName: null,
        patientlastName: null,
        patientphoneNo: null,
        patientemailId: null,
        appealBy: null,
        altphone: null,
        landLineNo: null,
        patientlandLineNo: null,
        patientaltphone: null,
        picName: null,
        signatureName: null,
        stateMedicalCouncil: null,
        countryType: null,
        dateOfBirth: null,
        universityName: null,
        qualification: null,
        imrNumber: null,
        smcCode: null
    },
    {
        yearInfo: 2021,
        regDate: '07/10/2021',
        doctorId: 12473553,
        salutation: null,
        firstName: 'YASHASWI  SINGH',
        middleName: null,
        lastName: null,
        phoneNo: null,
        emailId: null,
        gender: null,
        bloodGroup: null,
        parentName: 'UPENDRA KUMAR SINGH',
        birthDate: null,
        isNewDoctor: false,
        checkExistingUser: false,
        birthDateStr: '01/03/1985',
        birthPlace: null,
        nationality: null,
        eligbleToVote: null,
        adharNo: null,
        uprnNo: null,
        doctorEducationId: null,
        college: '',
        doctorDegree: '',
        university: '',
        otherSubject: null,
        monthOfPass: null,
        yearOfPassing: '',
        smcId: 23,
        registrationDate: null,
        registrationNo: '96060',
        smcName: 'Uttar Pradesh Medical Council',
        homeAddress: null,
        officeAddress: null,
        address: 'MAA CHARATABLE HOSPITAL RAMPURMAHABAL KHORIPAKAR, BALLIA-277001 UTTAR PRADESH',
        officeaddress: null,
        addressLine1: 'MAA CHARATABLE HOSPITAL RAMPURMAHABAL KHORIPAKAR, BALLIA-277001 UTTAR PRADESH',
        addressLine2: null,
        economicStatus: null,
        city: null,
        state: null,
        country: null,
        pincode: null,
        photos: null,
        doctRegistrationNo: null,
        universityId_view: null,
        universityId: null,
        monthandyearOfPass: '',
        passoutCollege: null,
        collegeId: null,
        stateId: null,
        catagory: null,
        catagory_view: 'N/A',
        role: null,
        registrationDatePrevious: null,
        registrationNoPrevious: null,
        smcNamePrevious: null,
        uprnNoPrevious: null,
        removedStatus: null,
        removedOn: null,
        restoredStatus: null,
        restoredOn: null,
        remarks: null,
        regnNo: null,
        smcIds: null,
        trasanctionStatus: null,
        addlqual1: '',
        addlqualyear1: '',
        addlqualuniv1: '',
        addlqual2: '',
        addlqualyear2: '',
        addlqualuniv2: '',
        addlqual3: '',
        addlqualyear3: '',
        addlqualuniv3: '',
        patientfirstName: null,
        patientmiddleName: null,
        patientlastName: null,
        patientphoneNo: null,
        patientemailId: null,
        appealBy: null,
        altphone: null,
        landLineNo: null,
        patientlandLineNo: null,
        patientaltphone: null,
        picName: null,
        signatureName: null,
        stateMedicalCouncil: null,
        countryType: null,
        dateOfBirth: null,
        universityName: null,
        qualification: null,
        imrNumber: null,
        smcCode: null
    }
]